# target.properties file updated with values for missing tokens
# Mon Mar 18 13:59:00 CDT 2024
# Properties file for environment specific build tokens
%%TARGET%%=dev
#######################################################
##SYSTEM DEFAULTS
#######################################################
%%ASC_DEFAULT_APP_FILEPATH%%=\\andc1wapp0137.ds.sjhs.com\\AppAggregation\\
%%ASC_AD_DEFAULT_SSL_PORT%%=636
#######################################################
##APPLICATION: STAR
#######################################################
%%ASC_STAR_FEEDFILE_NAME%%=Star.csv
%%ASC_STAR_ALBIR_FEEDFILE_NAME%%=Star_Albir.csv
#######################################################
# Invision-TNNAS-Attestation
#######################################################
%%ASC_INVISION_TNNAS_ATTESTATION_ACCOUNTS_FEEDFILE_NAME%%=Invision-TNNAS-Attestation.csv
%%ASC_INVISION_TNNAS_ATTESTATION_GROUPS_FEEDFILE_NAME%%=Invision-TNNAS-Attestation-Groups.csv
#######################################################
# Invision-TXAUS-Attestation
#######################################################
%%ASC_INVISION_TXAUS_ATTESTATION_ACCOUNTS_FEEDFILE_NAME%%=Invision-TXAUS-Attestation.csv
%%ASC_INVISION_TXAUS_ATTESTATION_GROUPS_FEEDFILE_NAME%%=Invision-TXAUS-Attestation-Groups.csv
#######################################################
# Tableau WebService Integration 
#######################################################
%%TABLEAU-BASEURL%%=https://tableau-dev.ascension.org/api/
%%TABLEAU-AUTHURL%%=/auth/signin
%%TABLEAU-VERSION%%=3.18
#######################################################
# Tableau WebService Integration - AscensionNational
#######################################################
%%TABLEAU-AN-USERNAME%%=DS\\svcsail
%%TABLEAU-AN-USERPASSWORD%%=bad-pwd
%%TABLEAU-AN-SITENAME%%=AscensionNational
%%TABLEAU-AN-LUID%%=25384736-77b2-43a1-8514-44598f000d24
#######################################################
# REQUESTOR CONSENT FORM LOCATION
#######################################################
%%ASC_CONSENT_FORM_FILENAME%%=AscensionCredentialTermsforNonAssociates.pdf
%%ASC_CONSENT_FROM_LOCATION%%=D:\\Files\\EmailAttachments\\AscensionCredentialTermsforNonAssociates.pdf
######################################################
# Azure
#######################################################
%%AZURE_CLIENT_SECRET%%=2:ACP:ipmHTTFmFMxXspj7V/So/2EIDE4fia3x51YPHMwvoLVLpy/flJinZ901M4pwqKktLCBcstG396oYfuFGca/6VA==
%%AZURE_CLIENT_ID%%=40955e77-6b83-42a8-a411-4d676644aae1
%%AZURE_DOMAIN_NAME%%=ascension-dev.org
%%MAX-THREAD-COUNT%%=4
#######################################################
# AD Connectors
#######################################################
%%IQSERVICE_HOST%%=ANDC1WAPP0137.ds.sjhs.com
%%IQSERVICE_PWD%%=2\:ACP\:+uiE\/Jg4TJxRZ12S\/JDYpmC4G1V6\/IqsAlu5VheGgpgKM0uF7BYSkDQheT5GYmuC
%%IQSERVICE_USER%%=ds\\sailpointtomcat-ds
%%AD_WIGLE_USER%%=WFSI\\spiq-wigle-pwc-dev
%%AD_WIGLE_PWD%%=2\:ACP\:D18E3zVBJHTvTmgBtbXu4pne1y\/JS1EvJhM5ikDSXyM\=
%%AD_WIAPP_USER%%=CORPROOT\\sailpoint-wiapp-dev
%%AD_WIAPP_PWD%%=2\:ACP:gbIe+MaSh6INdEc6K6YNx44pkzvVUosGTDHm9UuzVFKliql2jm2QHLcRb6xwmEAG
%%AD_OKTUL_USER%%=SJMC\\spiq-oktul-pwc-dev
%%AD_OKTUL_PWD%%=2\:ACP\:Ds9Z8PaXzJkyD3ZyWY4FN/YnRWByDweWhQ9MVbOqYeI\=
%%AD_MIROC_USER%%=CRITTENTON-NET\\spiq-miroc-pwc-dev
%%AD_MIROC_PWD%%=2\:ACP\:CojFgAZViHnJYaX2HwFKAvAiadhoacln6GTwzalOLsM\=
%%AD_KSWIC_USER%%=VCHS_NT_DOMAIN\\spiq-kswic-pwc-dev
%%AD_KSWIC_PWD%%=2\:ACP\:c+K7FX3dUDYeGZjpeKZMDP6ZNeivJdVH8Ugxw6zrM48\=
%%AD_DS_USER%%=DS\\sailpoint-ds-pwc-dev
%%AD_DS_PWD%%=2\:ACP\:Xu/FzGW5vA0EPrRuMIq/HMNLeaaVcRd6f4tmxBZU33Dx387uSmmL9z\/jTNLbVrV5
%%AD_AHSCN_USER%%=ALEXIAN\\spiq-ahscn-pwc-dev
%%AD_AHSCN_PWD%%=2\:ACP\:gfFfeOWmOOAu7XedML0DgPQdD32if2Nd99R+PgSU0bs\=
%%AD_AHMFM_USER%%=MEDXCELFM\\spiq-medxc-pwc-dev
%%AD_AHMFM_PWD%%=2\:ACP\:YPY2YzLCUcihby27oFgOxpMYVfr/FPVvfUzBmzeppEY\=
%%AD_ACHMO_USER%%=ABSALPHA4100\\sailpoint-acmho-dev
%%AD_ACHMO_PWD%%=2\:ACP\:KTVlO9TyywpQqP56n6R4xBKu6G2U27ZKJxCw64BYyzdZ8F772ZorN879ZQjf91Ha
%%AD_AMITA_USER%%=AMITA\\sailpointdev-AMITA
%%AD_AMITA_PWD%%=2\:ACP:Snd2fUmPlx6SevXXr5GptGxAUuC2npj4qJzctNl8DyQ\=
%%AD_PRESENCEHEALTH_PWD%%=1\:ACP\:Ri+NQ3ku2DUuirJDEbwX/brB5PtwW80o3+PM4YSAlIvLcwO1jkNntNDqIJqJm3fp
%%AD_PRESENCEHEALTH_USER%%=presencehealth\\S_sailpoint-PRESENCE
%%AD_ARCHIVE_PWD%%=1\:ACP\:ZmUUkWK0ddd2e3XbFFv6DEyIwOEJKEmrboeY9qTjNgc\=
%%AD_ARCHIVE_USER%%=archive\\sailpoint-archive
