#######################################################
# SAML Configuration
#######################################################
/Configuration[@name\='SAML']/Attributes/Map/entry[@key\='IdentityNow']/value/SAMLConfig/@assertionConsumerService=%%IIQSAML_ASSERTIONCONSUMERSERVICE%%
/Configuration[@name\='SAML']/Attributes/Map/entry[@key\='IdentityNow']/value/SAMLConfig/@bindingMethod=%%IIQSAML_BINDINGMETHOD%%
/Configuration[@name\='SAML']/Attributes/Map/entry[@key\='IdentityNow']/value/SAMLConfig/@entityId=%%IIQSAML_ENTITYID%%
/Configuration[@name\='SAML']/Attributes/Map/entry[@key\='IdentityNow']/value/SAMLConfig/@idpServiceUrl=%%IIQSAML_IDPSERVICEURL%%
/Configuration[@name\='SAML']/Attributes/Map/entry[@key\='IdentityNow']/value/SAMLConfig/@issuer=%%IIQSAML_ISSUER%%
/Configuration[@name\='SAML']/Attributes/Map/entry[@key\='IdentityNow']/value/SAMLConfig/@nameIdFormat=%%IIQSAML_NAMEIDFORMAT%%
/Configuration[@name\='SAML']/Attributes/Map/entry[@key\='IdentityNow']/value/SAMLConfig/IdpPublicKey[.]=%%IIQSAML_IDPPUBLICKEY%%
/Configuration[@name\='SAML']/Attributes/Map/entry[@key\='IdentityNow']/value/SAMLConfig/RuleRef/Reference/@name=%%IIQSAML_RULEREFNAME%%

#######################################################
# AD-DS - Configuration
#######################################################
# IQ Service Settings
/Application[@name\='AD-DS']/Attributes/Map/entry[@key\='IQServiceConfiguration']/value/List/Map/entry[@key\='IQServiceHost']/@value=%%IQSERVICE_HOST%%
/Application[@name\='AD-DS']/Attributes/Map/entry[@key\='IQServiceConfiguration']/value/List/Map/entry[@key\='IQServicePort']/@value=%%IQSERVICE_PORT%%
/Application[@name\='AD-DS']/Attributes/Map/entry[@key\='IQServiceConfiguration']/value/List/Map/entry[@key\='IQServicePassword']/@value=%%IQSERVICE_PWD%%
/Application[@name\='AD-DS']/Attributes/Map/entry[@key\='IQServiceConfiguration']/value/List/Map/entry[@key\='IQServiceUser']/@value=%%IQSERVICE_USER%%
%%AD_DS_USER%%=DS\\sailpoint-ds
%%AD_DS_PWD%%=1\:ACP\:iPbkgV0Z210rlC4CdCtF6ECIQjozq8f60QRLrH/J2I+HL0L7jTNJVrIOrQgUQRep
%%AD-DS_AHCHM_DC_LIST%%=<List><String>ANDC1WADC0162.AHCHM.DS.SJHS.COM</String></List>
%%AD-DS_AHDOC_DC_LIST%%=<List><String>ANDC1WADC0163.AHDOC.DS.SJHS.COM</String></List>
%%AD-DS_AHIS_DC_LIST%%=<List><String>ANDC1WADC0164.AHIS.DS.SJHS.COM</String></List>
%%AD-DS_AHNAT_DC_LIST%%=<List><String>ANDC1WADC0165.AHNAT.DS.SJHS.COM</String></List>
%%AD-DS_AHSCN_DC_LIST%%=<List><String>ANDC1WADC0166.AHSCN.DS.SJHS.COM</String></List>
%%AD-DS_ALBIR_DC_LIST%%=<List><String>ANDC1WADC0167.ALBIR.DS.SJHS.COM</String></List>
%%AD-DS_ALMOB_DC_LIST%%=<List><String>ANDC1WADC0169.ALMOB.DS.SJHS.COM</String></List>
%%AD-DS_CTBRI_DC_LIST%%=<List><String>AHWADCTXPLA022.CTBRI.DS.SJHS.COM</String></List>
%%AD-DS_DCWAS_DC_LIST%%=<List><String>ANDC1WADC0174.DCWAS.DS.SJHS.COM</String></List>
%%AD-DS_DS_DC_LIST%%=<List><String>ANDC1WADC0175.DS.SJHS.COM</String></List>
%%AD-DS_FLJAC_DC_LIST%%=<List><String>ANDC1WADC0177.FLJAC.DS.SJHS.COM</String></List>
%%AD-DS_FLPEN_DC_LIST%%=<List><String>ANDC1WADC0176.FLPEN.DS.SJHS.COM</String></List>
%%AD-DS_ILARL_DC_LIST%%=<List><String>ANDC1ADC0179.ILARL.DS.SJHS.COM</String></List>
%%AD-DS_INEVA_DC_LIST%%=<List><String>ANDC1WADC0171.INEVA.DS.SJHS.COM</String></List>
%%AD-DS_ININD_DC_LIST%%=<List><String>ANDC1WADC0180.ININD.DS.SJHS.COM</String></List>
%%AD-DS_INMSC_DC_LIST%%=<List><String>ANDC1WADC0181.INMSC.DS.SJHS.COM</String></List>
%%AD-DS_MISAG_DC_LIST%%=<List><String>ANDC1WADC0187.MISAG.DS.SJHS.COM</String></List>
%%AD-DS_MDBAL_DC_LIST%%=<List><String>ANDC1WADC0182.MDBAL.DS.SJHS.COM</String></List>
%%AD-DS_MIGRA_DC_LIST%%=<List><String>ANDC1WADC0184.MIGRA.DS.SJHS.COM</String></List>
%%AD-DS_MIKAL_DC_LIST%%=<List><String>ANDC1WADC0185.MIKAL.DS.SJHS.COM</String></List>
%%AD-DS_MOSTL_DC_LIST%%=<List><String>ANDC1WADC0189.MOSTL.DS.SJHS.COM</String></List>
%%AD-DS_NYAMS_DC_LIST%%=<List><String>ANDC1WADC0121.NYAMS.DS.SJHS.COM</String><String>ANDC2WADC0121.NYAMS.DS.SJHS.COM</String></List>
%%AD-DS_NYBIN_DC_LIST%%=<List><String>ANDC1WADC0192.NYBIN.DS.SJHS.COM</String></List>
%%AD-DS_SJHS_DC_LIST%%=<List><String>ANDC1WADC0193.SJHS.DS.SJHS.COM</String></List>
%%AD-DS_TNNAS_DC_LIST%%=<List><String>ANDC1WADC0195.TNNAS.DS.SJHS.COM</String></List>
%%AD-DS_TXAUS_DC_LIST%%=<List><String>ANDC1WADC0196.TXAUS.DS.SJHS.COM</String></List>
%%AD-DS_TXWAC_DC_LIST%%=<List><String>ANDC1WADC0197.TXWAC.DS.SJHS.COM</String></List>
%%AD-DS_WIMIL_DC_LIST%%=<List><String>ANDC1WADC0200.WIMIL.DS.SJHS.COM</String></List>

#######################################################
# AD Domain Controller Ports
#######################################################
%%AD-ACMHO_MISTRHGHTS_PORT%%=389
%%AD-AHMFM_MEDXCELFM_PORT%%=636
%%AD-AHSCN_ABSM_PORT%%=636
%%AD-AMITA_AMITA_PORT%%=389
%%AD-DS_AHCHM_PORT%%=636
%%AD-DS_AHDOC_PORT%%=636
%%AD-DS_AHIS_PORT%%=636
%%AD-DS_AHNAT_PORT%%=636
%%AD-DS_AHSCN_PORT%%=636
%%AD-DS_ALBIR_PORT%%=636
%%AD-DS_ALMOB_PORT%%=636
%%AD-DS_CTBRI_PORT%%=636
%%AD-DS_DCWAS_PORT%%=636
%%AD-DS_DS_PORT%%=636
%%AD-DS_FLJAC_PORT%%=636
%%AD-DS_FLPEN_PORT%%=636
%%AD-DS_ILARL_PORT%%=636
%%AD-DS_INEVA_PORT%%=636
%%AD-DS_ININD_PORT%%=636
%%AD-DS_INMSC_PORT%%=636
%%AD-DS_MISAG_PORT%%=636
%%AD-DS_MDBAL_PORT%%=636
%%AD-DS_MIGRA_PORT%%=636
%%AD-DS_MIKAL_PORT%%=636
%%AD-DS_MOSTL_PORT%%=636
%%AD-DS_NYAMS_PORT%%=389
%%AD-DS_NYBIN_PORT%%=636
%%AD-DS_SJHS_PORT%%=636
%%AD-DS_TNNAS_PORT%%=636
%%AD-DS_TXAUS_PORT%%=636
%%AD-DS_TXWAC_PORT%%=636
%%AD-DS_WIMIL_PORT%%=636
%%AD-KSWIC_MRHC_PORT%%=636
%%AD-KSWIC_MTC_PORT%%=636
%%AD-KSWIC_VIA-CHRISTI_PORT%%=636
%%AD-MIROC_CRITTENTON_PORT%%=636
%%AD-OKTUL_FR_PORT%%=636
%%AD-OKTUL_JPMMC_PORT%%=636
%%AD-OKTUL_SJMC_PORT%%=636
%%AD-PRESENCEHEALTH_PRESENCEHEALTH_PORT%%=389
%%AD-WIAPP_AFFINITY_PORT%%=389
%%AD-WIAPP_CORPROOT_PORT%%=389
%%AD-WIAPP_MINISTRY_PORT%%=389
%%AD-WFSI_WFSI_PORT%%=636
%%AD-AID_PORT%%=389
#######################################################
# GSUITE Connectors
#######################################################
/Application[@name='GSuite']/Attributes/Map//entry[@key='clientID']@value=%%GSUITE_CLIENT_ID%%
/Application[@name='GSuite']/Attributes/Map//entry[@key='clientSecret']@value=%%GSUITE_CLIENT_SECRET%%
/Application[@name='GSuite']/Attributes/Map//entry[@key='refreshToken']@value=%%GSUITE_REFRESH_TOKEN%%
