PROD-PSFT.URL=jdbc:oracle:thin:@ascnexa03pr-vwbip-scan.opc.oracleoutsourcing.com:1521/ASCNHPRD
PROD-PSFT.DRIVER=oracle.jdbc.driver.OracleDriver
PROD-PSFT.USERNAME=AH_ERP_SBT
PROD-PSFT.PASSWORD=SpNt#2019

DEV-PSFT.URL=jdbc:sqlserver://ANDC1WSQL0140.ds.sjhs.com:1433;databaseName=identityiq
DEV-PSFT.DRIVER=com.microsoft.sqlserver.jdbc.SQLServerDriver
DEV-PSFT.USERNAME=identityiq
DEV-PSFT.PASSWORD=pb{wy6vX


